steps:
  - name: build
    image: debian
    commands:
      - echo "test content" > myfile
    when:
      - event: manual
  - name: a-test-step
    image: debian
    commands:
      - cat myfile
    when:
      - event: manual

  - run-greet:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix run --store unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt .#exit0 -L
    volumes:
      - /nix:/mnt/nix:ro