matrix:
  ami:
    - ami
    - amiDebug

steps:
  - name: build
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build .#${ami} -L

  - name: create ami
    image: amazonlinux
    commands:
      - ./create-ami-wp.py --s3-key ${ami}
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]