matrix:
  flake:
    - test
    - bootstrap

steps:
  - name: build
    image: nixos/nix
    commands:
      - echo hello
      # - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      # - echo "extra-substituters = https://binary-cache-6b1b4a.flakery.xyz" >> /etc/nix/nix.conf
      # - echo "extra-trusted-public-keys = binary-cache-6b1b4a.flakery.xyz/:Du7IeCqQQiJpvdhizPnX2ZN2GTlMeUR7C+r9x8Xkjz0=" >> /etc/nix/nix.conf
      # # add ${SSH_PRIVATE_KEY_B64} to /root/.ssh/id_rsa
      # - mkdir -p ~/.ssh
      # - echo ${SSH_PRIVATE_KEY_B64} | base64 -d > ~/.ssh/id_rsa
      # - chmod 600 ~/.ssh/id_rsa
      # - ssh-keyscan binary-cache-6b1b4a.flakery.xyz >> ~/.ssh/known_hosts
      # - nix build .#${flake} -L --print-out-paths  | xargs -I{} nix copy --to flakery@35.164.151.132 {}

  