matrix:
  flake:
    - test
    - bootstrap

steps:
  - name: build
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - echo echo "extra-substituters = https://binary-cache-6b1b4a.flakery.xyz/" >> /etc/nix/nix.conf
      - echo "extra-trusted-public-keys = binary-cache-6b1b4a.flakery.xyz/:Du7IeCqQQiJpvdhizPnX2ZN2GTlMeUR7C+r9x8Xkjz0=" >> /etc/nix/nix.conf
      - nix build --store "unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" .#${flake} -L --print-out-paths
    volumes:
      - /nix:/mnt/nix:ro
  