matrix:
  flake:
    - ami
    - test
    - bootstrap

steps:
  - name: build
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build --store "unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" .#${flake} -L
    volumes:
      - /nix:/mnt/nix:ro
  