variables:
  user_safe_env: &user_safe_env
    BINARY_CACHE_HOST: "binary-cache-6b1b4a.flakery.xyz"
    FLAKE: "github:getflakery/bootstrap#nixosConfigurations.grafana.config.system.build.toplevel"
    TEMPLATE_ID: "4c6e0786-97c9-4d1b-8687-ca8761af9cdd"
    ENCRYPTION_KEY: "0939865eee0fff95518bb8f0ac64cafe5d9d04429b51d55a82d3a42ea5da5b1f"

steps:
  - name: prepare
    image: nixos/nix
    environment:
      <<: *user_safe_env
      TURSO_TOKEN:
        from_secret: TURSO_TOKEN
      SSH_PRIVATE_KEY_B64:
        from_secret: SSH_PRIVATE_KEY_B64
      NIX_SSH_OPTS: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' 
    secrets:
      - TURSO_TOKEN
      - SSH_PRIVATE_KEY_B64
    commands:
      - rm /etc/ssl/certs/ca-bundle.crt
      - cp /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt nix run --store "unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" github:getflakery/bootstrap/2967cd71b3201755c0065bc3e7f02ec5e309d0d8#bootstrap -- --write-files --turso-token $TURSO_TOKEN --template-id $TEMPLATE_ID --encryption-key $ENCRYPTION_KEY
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - echo "extra-substituters = https://$BINARY_CACHE_HOST" >> /etc/nix/nix.conf
      - echo "extra-trusted-public-keys = $BINARY_CACHE_HOST/:Du7IeCqQQiJpvdhizPnX2ZN2GTlMeUR7C+r9x8Xkjz0=" >> /etc/nix/nix.conf
      - nix build $FLAKE -L --print-out-paths --impure > out.txt
      - mkdir -p ~/.ssh
      - echo $SSH_PRIVATE_KEY_B64 | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - cat out.txt | xargs -I {} nix copy --substitute-on-destination --to "ssh://flakery@35.93.144.57?ssh-option=${NIX_SSH_OPTS}" {}

    volumes:
      - /nix:/mnt/nix:ro
skip_clone: true
