
steps:

  - name: prepare
    image: nixos/nix
    environment:
    commands:
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - rm /etc/ssl/certs/ca-bundle.crt
      - cp /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt nix run --store "unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" github:getflakery/bootstrap/2967cd71b3201755c0065bc3e7f02ec5e309d0d8#bootstrap -- --write-files --turso-token $TURSO_TOKEN --template-id $TEMPLATE_ID --encryption-key $ENCRYPTION_KEY
      - nix build --store "unix:///mnt/nix/var/nix/daemon-socket/socket?root=/mnt" $FLAKE -L --impure --no-write-lock-file
    volumes:
      - /nix:/mnt/nix:ro
skip_clone: true
