variables:
  - &vol '/mnt/nix:/mnt/nix'
steps:
  - test:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build --eval-store local --store /mnt/nix .#test -L
    volumes:
      - *vol

