
steps:
  - name: testssh
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - echo "extra-substituters = https://binary-cache-6b1b4a.flakery.xyz" >> /etc/nix/nix.conf
      - echo "extra-trusted-public-keys = binary-cache-6b1b4a.flakery.xyz/:Du7IeCqQQiJpvdhizPnX2ZN2GTlMeUR7C+r9x8Xkjz0=" >> /etc/nix/nix.conf
      - mkdir -p ~/.ssh
      - echo $SSH_PRIVATE_KEY_B64 | base64 -d > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - ssh-keyscan 35.164.151.132 >> ~/.ssh/known_hosts
      - ssh flakery@35.164.151.132 echo "hello"
    secrets:
      - ssh_private_key_b64