name: Build AMI's

on:
  pull_request:
  push:
    branches: [master]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  
jobs:
  build-amis:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        ami:
          - name: ami
            s3-key: ami
          - name: amiDebug
            s3-key: amiDebug
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Create AMI
        run: ./create-ami.py --flake .#${{ matrix.ami.name }} --s3-key ${{ matrix.ami.s3-key }}
